name: Continuous Deployment (CD)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2

      - name: Set up NodeJS environment
        uses: actions/setup-node@v2

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.REACT_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 13.112.225.81 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REACT_KEY }}

      - name: Set environment variables
        run: |
          echo "REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}" >> .env
          echo "REACT_APP_RAYGUN_KEY=${{ secrets.REACT_APP_RAYGUN_KEY }}" >> .env

      - name: Install package dependencies
        run: npm install --force

      - name: Build React App
        run: npm run build

      - name: Check .env file
        run: cat .env

      - name: Deploy to EC2
        run: |
          # Run any build commands, if needed
          export CI=false
          npm run build
          # Copy the built React app to your EC2 instance using SCP
          scp -r ./build/* ubuntu@13.112.225.81:/home/ubuntu/autodeploy
